export const FETCH_CONTENT = 'FETCH_CONTENT'
export const FETCH_CONTENT_FAILED = 'FETCH_CONTENT_FAILED'
export const FETCH_CONTENT_FUFILLED = 'FETCH_CONTENT_FUFILLED'

export const SEARCH_CONTENT = 'SEARCH_CONTENT'
